testlevel = [
    "                  ",
    "                  ",
    "  WWWWSWWW        ",
    "           T      ",
    "  T  P     T      ",
    "           T      ",
    " U U U   W        ",
    "         W        ",
    " U   WWTWW        ",
    "                  ",
    " U                ",
    "  SSSSSSSSSSSS    ",
    "  SSSSSSSSSSSS    ",
    "                  ",
    "         E        ",
    "                  ",
    "                  ",
    "                  ",
]  
level0 = [
    "WWWWWWWWWWWWWWWWWW",
    "WPWWWWWWWWWWWWWWWW",
    "W WWWWWKWWWWWWWWWW",
    "W WWWWW WWWWWWWWWW",
    "W WWWWW WWWWWWWWWW",
    "W     U    TWWWWWW",
    "W WWWWWWWW WWWWWWW",
    "W WWWWWWWW WWWWWWW",
    "W WWWWWWWW WWWWWWW",
    "W SWWWWWWWSWWWWWWW",
    "WDSWWWWWWW WWWWWWW",
    "WDSWWWWWWW   KWWWW",
    "W SWWWWWWWWWWWWWWW",
    "WEWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW",
]
level1 = [
    "WWWWWWWWWWWWWWWWWW",
    "WP     T   WWW   W",
    "WWWWWW WWW WWW W W",
    "WWWT   WWW     W W",
    "W    WWWWWWWWW W W",
    "W WWKW     WWWKS W",
    "W WWWW WWW WWWWW W",
    "W TWWW W         W",
    "W  WWW W WWWW WWUW",
    "WW WKW W SSWW WWWW",
    "WW     W WK    T W",
    "WWWWWSWW WWWWWWWWW",
    "W U             TW",
    "WWWWW WWWWWW WWWWW",
    "WWWWW   WW   WWWWW",
    "WWWWWDWWWWWWDWWWWW",
    "WWWWW        WWWWW",
    "WWWWWWWWEEWWWWWWWW",
]

level2 = [
    "WWWWWWWWWWWWWWWWWW",
    "W         WWWK   W",
    "WWWWWW W WKWWW W W",
    "WWW    W       W W",
    "W U  WWWWWWWWT W W",
    "W WWSWWWWWWWSKW  W",
    "W WWSW    WWSWWW W",
    "W  WSWDWW W      W",
    "WT SSWDWEEWKW  W W",
    "WW WWWDWWWWWWWWW W",
    "WW     W         W",
    "WW WSWWW WWWWWWWWW",
    "WWKW     U       W",
    "WWWWWTWWWWWW WWWWW",
    "WWWWW  WWWWT WWWWW",
    "WU WT   WW    W KW",
    "WWT   W    W    WW",
    "WWWWWWWWP WWWWWWWW",
]
level3 = [
    "WWWWWWWWWWWWWWWWWW",
    "WP         TWWWWWW",
    "WWWWWWWSWW WWWWWWW",
    "WW     KWW WWWWWWW",
    "WW WWWW WW WSSSWWW",
    "WW WWW       WUWWW",
    "WW WWWWWSWWWWWWWWW",
    "WW    T   SSSSSWWW",
    "WW WWWWWWWWWWWSWWW",
    "WW WWWW SSSSSSSWWW",
    "WW WWWWSWWWWWWWWWW",
    "WW WWWWS UWWKWWWWW",
    "WW     WWWWW WWWWW",
    "WWWWWT          KW",
    "WWWWWWW WWWWWWWWWW",
    "WWWWD    TDWWWWWWW",
    "WWWWEWWWWWEWWWWWWW",
    "WWWWWWWWWWWWWWWWWW",
    ]
level4 = [
    'WWWWWWWWWWWWWWWWWW',
    'W              KTW',
    'W W WWWWWWWWWWWWSW',
    'W W         KWKW W',
    'W W WWWWWWWWWW W W',
    'WWW         W  W W',
    'WU  WWWWWWW W W  W',
    'WWW       W   W WW',
    'W W WWWWW WWW W DE',
    'W W W   W  UW W DE',
    'W W W P    TW W WW',
    'W W W  WWWWW  W  W',
    'W W WWW      WKW W',
    'W W     WWWWWW S W',
    'W W      SKW   W W',
    'W WWW WWWW W WWW W',
    'W                W',
    'WWWWWWWWWWWWWWWWWW']

level5 =[
    'WWWWWWWWWWWWWWWWWW',
    'WPS              W',
    'W W W WWWWWWWWWW W',
    'W W W W        W W',
    'W W W W   KW  UW W',
    'W W W WWWWWW WWW W',
    'W W W        WK  W',
    'W W WWWWWWWW WWWWW',
    'W W       KW   DDE',
    'W W WWWWWWWW WWWWW',
    'W W W     UW     W',
    'W W W WWWWWW WWW W',
    'W W W W      WUW W',
    'W W W W WWWW W W W',
    'W W W W   UW W W W',
    'W W W WWWWWW W W W',
    'W   W       T    W',
    'WWWWWWWWWWWWWWWWWW']



#LEVEL LIST \/
levels = [level0, level1, level2, level3, level4, level5,]
#levels = [testlevel]
